insert into CACHE_ISTANZA_SCHEDA(VARIABILE, VALORE)
select
    m.NG_MODEL as VARIABILE, COALESCE (TO_CHAR(m.NG_VALUE),TO_CHAR(a.ANSWER), null) VALORE
from ANSWERS a
join TMP_MODELO_FM2_FM3 m on a.REF_TMPLANSWER = m.CODICE_ELEMENTO
where
    REF_ACTIVITY in (select ID from ACTIVITIES where REF_ACTYPE in (select id from TMPLCOMPONENTS WHERE CODE = 'schedaComorbilitaCIRS'));


select FN_GENERA_JSON_DA_CACHE() FROM dual;
