CREATE TABLE "DYNAMICFORMS_SVI"."ACTIVITIES"
 (	"ID" NUMBER(10,0) NOT NULL ENABLE,
"SUBJECT_ID" VARCHAR2(128),
"ENTRY_DATETIME" DATE,
"SITE" VARCHAR2(4000),
"STATE" NUMBER(1,0) DEFAULT 0,
"PUBLISHED_DATETIME" DATE,
"REPO_REGISTRYOBJ_ID" NUMBER(10,0),
"REPO_REPOSITORYITEM_ID" NUMBER(10,0),
"EXTERNAL_REFERENCE" VARCHAR2(128),
"REF_ACTYPE" NUMBER(10,0) NOT NULL ENABLE,
"REF_SOURCE" NUMBER(10,0) NOT NULL ENABLE,
"XMLDATA" CLOB,
"REF_PARENT" NUMBER(10,0),
"ROW_VERSION" NUMBER DEFAULT 0,
"DELETED" NUMBER(1,0) DEFAULT 0,
"INSERT_DATETIME" DATE,
"INSERT_USER" VARCHAR2(128),
"LASTUPDATE_DATETIME" DATE,
"LASTUPDATE_USER" VARCHAR2(128),
"CANCEL_DATETIME" DATE,
"CANCEL_USER" VARCHAR2(128),
"EXTERNAL_ID" NUMBER(18,0),
"EXTERNAL_TAB" VARCHAR2(128),
"VERSION" NUMBER(10,0),
 CHECK (
STATE IN (0, 1)
) ENABLE,
 CHECK (
DELETED IN (0, 1)
) ENABLE,
 CONSTRAINT "PK_ACTIVITIES" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
 CONSTRAINT "FK_ACTIVITY_ACTIVITYTYPE_1" FOREIGN KEY ("REF_ACTYPE")
  REFERENCES "DYNAMICFORMS_SVI"."ACTIVITYTYPES" ("ID") ENABLE,
 CONSTRAINT "FK_ACTIVITY_ACTIVITY_1" FOREIGN KEY ("REF_PARENT")
  REFERENCES "DYNAMICFORMS_SVI"."ACTIVITIES" ("ID") ENABLE,
 CONSTRAINT "FK_ACTIVITY_SOURCE_1" FOREIGN KEY ("REF_SOURCE")
  REFERENCES "DYNAMICFORMS_SVI"."SOURCES" ("ID") ENABLE
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DYNAMIC_FORMS_SVI"
LOB ("XMLDATA") STORE AS BASICFILE (
TABLESPACE "DYNAMIC_FORMS_SVI" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
NOCACHE LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))

 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."ID" IS 'Identificativo numerico assegnato dal sistema'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."SUBJECT_ID" IS 'Soggetto della scheda'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."ENTRY_DATETIME" IS 'Data/ora di registrazione dell''attività'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."SITE" IS 'Luogo (testo libero) riferito alla registrazione della scheda'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."STATE" IS 'Definisce in che stato sia l''attività: 0=Bozza, 1=Confermata'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."PUBLISHED_DATETIME" IS 'Data/ora in cui l''attività è stata resa definitiva (pubblicata)'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."REPO_REGISTRYOBJ_ID" IS 'Riferimento a REGISTRY_OBJECTS.ID di IE-Repository'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."REPO_REPOSITORYITEM_ID" IS 'Riferimento a REPOSITORY_ITEMS.ID di IE-Repository'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."EXTERNAL_REFERENCE" IS 'External reference (su HOPERA: CPOE_ORDERS_PLACED.FM_EXTERNAL_ID)'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."REF_ACTYPE" IS 'Identifica l''appartenenza dell''occorrenza di ACTIVITY ad un''occorrenza di ACTIVITYTYPE'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."REF_SOURCE" IS 'Identifica l''occorrenza di SOURCE (sistema origine) che ha dato luogo all''occorrenza di ACTIVITY'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."XMLDATA" IS 'Riporta l''XML generato in fase di creazione report'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."EXTERNAL_ID" IS 'Riferimento id sistema esterno di origine'
 COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITIES"."EXTERNAL_TAB" IS 'Riferimento tabella sistema esterno di origine'
