
  CREATE TABLE "DYNAMICFORMS_SVI"."ACTIVITY_METADATA"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"REF_ACTIVITY" NUMBER(10,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_ACTIVITY_METADATA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_ACTMETADATA_ACTIVITY_1" FOREIGN KEY ("REF_ACTIVITY")
	  REFERENCES "DYNAMICFORMS_SVI"."ACTIVITIES" ("ID") ENABLE,
	 CONSTRAINT "FK_ASS_27" FOREIGN KEY ("ID")
	  REFERENCES "DYNAMICFORMS_SVI"."METADATA" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITY_METADATA"."ID" IS 'Identificativo numerico assegnato dal sistema'
   COMMENT ON TABLE "DYNAMICFORMS_SVI"."ACTIVITY_METADATA"  IS 'Metadati di Activity con riferimento a KEY, VALUE, REF_TMPLCOMPONENT in METADATA'
