
  CREATE TABLE "DYNAMICFORMS_SVI"."ACTIVITYTYPES"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(300) NOT NULL ENABLE,
	"CATEGORY" CHAR(1 CHAR) NOT NULL ENABLE,
	"HAS_RATING" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CHART_MIN_Y" NUMBER(10,0),
	"CHART_MAX_Y" NUMBER(10,0),
	"RATING_IS_PROP" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"RATING_MAX_VALUE" NUMBER(10,0),
	"NOTE" VARCHAR2(4000),
	"TAG_XML_ACTIVITY" VARCHAR2(200),
	"TAG_XML_ACTIVITY_OUTCOME" VARCHAR2(200),
	"TAG_XML_ACTIVITY_SCORE" VARCHAR2(200),
	"STYLE_CSS" VARCHAR2(300),
	"STATUS" VARCHAR2(50) NOT NULL ENABLE,
	"VERSION" NUMBER(10,0) NOT NULL ENABLE,
	"FL_INCLUDE_SEARCH" NUMBER(1,0) DEFAULT 0, 
	"JAVASCRIPT_LIBRARY" VARCHAR2(300),
	"FL_ENABLE_DUAL_MONITOR" NUMBER(1,0) DEFAULT 0,
	"REF_ENTRY" NUMBER(10,0),
	 CHECK (
  CATEGORY IN ('A', 'C', 'E', 'N', 'R', 'S')
) ENABLE,
	 CHECK (
  HAS_RATING IN (0, 1)
) ENABLE,
	 CHECK (
  RATING_IS_PROP IN (0, 1)
) ENABLE,
	 CHECK (
  STATUS IN ('EDITING', 'PUBLISHED')
) ENABLE,
	 CONSTRAINT "PK_ACTIVITYTYPES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CHECK (
  FL_INCLUDE_SEARCH IN (0, 1)
) ENABLE,
	 CONSTRAINT "FK_ASS_34" FOREIGN KEY ("ID")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLCOMPONENTS" ("ID") ENABLE,
	 CONSTRAINT "FK_ACTIVITYTYPE_ENTRY" FOREIGN KEY ("REF_ENTRY")
	  REFERENCES "DYNAMICFORMS_SVI"."ENTRIES" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."ID" IS 'Identificativo numerico assegnato dal sistema'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."NAME" IS 'Nome / Descrizione della tipologia'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."CATEGORY" IS 'Campo a valore vincolato che categorizza a sua volta le tipologie. I valori ammessi sono: C=Evento CSS; N=Annotazioni; R=Relazione Sociale; S=Scheda di Valutazione; A=Documenti/Allegati acquisiti (scannerizzati su pdf)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."HAS_RATING" IS 'Indica che le relative Activities prevedono la valorizzazione del campo RATING, tipicamente questo attributo vale 1 per le ACTIVITY di categoria S (Schede Valutative)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."CHART_MIN_Y" IS 'Configurazione valore minimo ordinate per rappresentazione grafica'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."CHART_MAX_Y" IS 'Configurazione valore massimo ordinate per rappresentazione grafica'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."RATING_IS_PROP" IS 'Indica se la gravità del paziente è direttamente proporzionale al punteggio del tipo di scheda'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."RATING_MAX_VALUE" IS 'Indica il valore massimo che il punteggio può assumere per la scheda'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."NOTE" IS 'Eventuali note della Scheda'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."TAG_XML_ACTIVITY" IS 'Indica il tag da utilizzare in XML per la radice delle schede'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."TAG_XML_ACTIVITY_OUTCOME" IS 'Indica il tag da utilizzare in XML per l''''esito delle schede'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."TAG_XML_ACTIVITY_SCORE" IS 'Indica il tag da utilizzare in XML per il punteggio delle schede'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."STYLE_CSS" IS 'Indica lo style css per il componente'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."STATUS" IS 'Indica lo stato della form: EDITING se ancora in fase di configurazione, PUBLISHED se confermata'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."VERSION" IS 'Versione della form: solo le schede in stato PUBLISHED hanno una versione'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."FL_INCLUDE_SEARCH" IS 'Indica se la scheda deve includere o meno il pannello di ricerca.'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."JAVASCRIPT_LIBRARY" IS 'Indica il nome della libraria javascript, caricata da risorsa esterna.'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."ACTIVITYTYPES"."FL_ENABLE_DUAL_MONITOR" IS 'Indica se tutte le domande di una attivita'' devono avere il tasto di mirror per il doppio schermo'
