
  CREATE TABLE "DYNAMICFORMS_SVI"."PARAM_VIEW_FILTER_MAPPINGS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"VIEW_COLUMN_NAME" VARCHAR2(200),
	"INIT_PARAM_XPATH" VARCHAR2(200),
	"REF_PARAM_VIEW" NUMBER(10,0) NOT NULL ENABLE,
	"ROW_VERSION" NUMBER DEFAULT 0,
	"DELETED" NUMBER(1,0) DEFAULT 0,
	"INSERT_DATETIME" DATE,
	"INSERT_USER" VARCHAR2(128),
	"LASTUPDATE_DATETIME" DATE,
	"LASTUPDATE_USER" VARCHAR2(128),
	"CANCEL_DATETIME" DATE,
	"CANCEL_USER" VARCHAR2(128),
	 CHECK (
  DELETED IN (0, 1)
) ENABLE,
	 CONSTRAINT "PK_PARAM_VIEW_FILTER_MAPPINGS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_PV_FILT_MAP_PARAMVIEW_1" FOREIGN KEY ("REF_PARAM_VIEW")
	  REFERENCES "DYNAMICFORMS_SVI"."PARAM_VIEWS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEW_FILTER_MAPPINGS"."VIEW_COLUMN_NAME" IS 'Nome della colonna della vista su cui applicare il filtro'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEW_FILTER_MAPPINGS"."INIT_PARAM_XPATH" IS 'Xpath dell''xml di inizializzazione da cui recuperare il valore per il filtro'
