
  CREATE TABLE "DYNAMICFORMS_SVI"."PARAM_VIEWS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(128),
	"VALUE" VARCHAR2(4000),
	"DESCRIPTION" VARCHAR2(4000),
	"ROW_VERSION" NUMBER DEFAULT 0,
	"DELETED" NUMBER(1,0) DEFAULT 0,
	"INSERT_DATETIME" DATE,
	"INSERT_USER" VARCHAR2(128),
	"LASTUPDATE_DATETIME" DATE,
	"LASTUPDATE_USER" VARCHAR2(128),
	"CANCEL_DATETIME" DATE,
	"CANCEL_USER" VARCHAR2(128),
	"EXTERNAL_ID" NUMBER(18,0),
	"FL_USE_FILTER_DATA" NUMBER(1,0) DEFAULT 0,
	"FL_USE_DICTIONARY_VALUES" NUMBER(1,0) DEFAULT 0,
	"ORDER_BY_COLUMN" VARCHAR2(128),
	"FL_ORDER_DESC" NUMBER(1,0) DEFAULT 0,
	 CHECK (
  DELETED IN (0, 1)
) ENABLE,
	 CONSTRAINT "PK_PARAM_VIEWS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."CODE" IS 'Codice/Parametro corrispondente alla Vista'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."VALUE" IS 'Vista o Datasource o Query da eseguire per popolare combo'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."DESCRIPTION" IS 'Descrizione della Vista/Datasource/Query'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."EXTERNAL_ID" IS 'Riferimento id sistema esterno di origine'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."FL_USE_DICTIONARY_VALUES" IS '0: utilizza View 1: utilizza valori dizionario da tabella DICTIONARY_VALUES'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."ORDER_BY_COLUMN" IS 'Indica  la colonna su cui fare ordinamento valori combo'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."PARAM_VIEWS"."FL_ORDER_DESC" IS 'Flag per order ASC|DESC, default ASC'
