
  CREATE TABLE "DYNAMICFORMS_SVI"."TMPLCOMPONENTS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(128),
	"BACKGROUND_IMAGE" VARCHAR2(128),
	"REF_GENERIC_COMP" NUMBER(10,0),
	"ROW_VERSION" NUMBER DEFAULT 0,
	"DELETED" NUMBER(1,0) DEFAULT 0,
	"INSERT_DATETIME" DATE,
	"INSERT_USER" VARCHAR2(128),
	"LASTUPDATE_DATETIME" DATE,
	"LASTUPDATE_USER" VARCHAR2(128),
	"CANCEL_DATETIME" DATE,
	"CANCEL_USER" VARCHAR2(128),
	"EXTERNAL_ID" NUMBER(18,0),
	"EXTERNAL_TAB" VARCHAR2(128),
	 CHECK (
  DELETED IN (0, 1)
) ENABLE,
	 CONSTRAINT "PK_TMPLCOMPONENTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_TMPLCOMP_TMPLCOMP_1" FOREIGN KEY ("REF_GENERIC_COMP")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLCOMPONENTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLCOMPONENTS"."ID" IS 'Identificativo numerico assegnato dal sistema'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLCOMPONENTS"."REF_GENERIC_COMP" IS 'Riferimento al componente da cui deriva il versionamento del componente stesso'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLCOMPONENTS"."EXTERNAL_ID" IS 'Riferimento id sistema esterno di origine'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLCOMPONENTS"."EXTERNAL_TAB" IS 'Riferimento tabella sistema esterno di origine'
