
  CREATE TABLE "DYNAMICFORMS_SVI"."TMPLITEMS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(4000),
	"REF_TMPLSECTION" NUMBER(10,0) NOT NULL ENABLE,
	"MANDATORY" NUMBER(1,0) DEFAULT 0,
	"NOTE" VARCHAR2(4000),
	"HIDDEN" NUMBER(1,0) DEFAULT 0,
	"COMPLEMENTARY_ITEM" NUMBER(10,0),
	"TAG_XML_QUESTION" VARCHAR2(200),
	"TAG_XML_QUESTION_RATING" VARCHAR2(200),
	"TAG_XML_QUESTION_DESC" VARCHAR2(200),
	"MANDATORY_TO_SEX" VARCHAR2(1),
	"STYLE_CSS" VARCHAR2(300),
	"NEW_LINE" NUMBER(1,0) DEFAULT 0,
	"POSITION_INDEX" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"COLUMNS_RADIOCHECK_GROUP" NUMBER(10,0),
	"FOLLOWED_BY_SEPARATOR" NUMBER(1,0) DEFAULT 0,
	"REF_ENTRY" NUMBER(10,0),
	"FL_SUMMARY_FIELD" NUMBER(1,0) DEFAULT 0,
	 CHECK (
  MANDATORY IN (0, 1)
) ENABLE,
	 CHECK (
  HIDDEN IN (0, 1)
) ENABLE,
	 CHECK (
  MANDATORY_TO_SEX IN ('F', 'M')
) ENABLE,
	 CHECK (
  NEW_LINE IN (0, 1)
) ENABLE,
	 CHECK (
  FOLLOWED_BY_SEPARATOR IN (0, 1)
) ENABLE,
	 CONSTRAINT "PK_TMPLITEMS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_ASS_14" FOREIGN KEY ("ID")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLCOMPONENTS" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLITEM_TMPLITEM_1" FOREIGN KEY ("COMPLEMENTARY_ITEM")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLITEMS" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLITEM_TMPLSECTION_1" FOREIGN KEY ("REF_TMPLSECTION")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLSECTIONS" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLITEM_ENTRY" FOREIGN KEY ("REF_ENTRY")
	  REFERENCES "DYNAMICFORMS_SVI"."ENTRIES" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."ID" IS 'Identificativo numerico assegnato dal sistema'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."VALUE" IS 'Valore dell''elemento della scheda (es. testo della domanda)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."REF_TMPLSECTION" IS 'Riferimento che identifica la sezione alla quale l''''item si riferisce'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."MANDATORY" IS 'Obbligo di risposta'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."NOTE" IS 'Eventuali note della domanda'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."HIDDEN" IS 'Valore che indica se la domanda deve essere visualizzata o meno'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."COMPLEMENTARY_ITEM" IS 'Riferimento alla domanda a cui è complementare. Una possibile risposta tra le 2 domande'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."TAG_XML_QUESTION" IS 'Indica il tag da utilizzare in XML per le domande'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."TAG_XML_QUESTION_RATING" IS 'Indica il tag da utilizzare in XML per il rating delle domande'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."TAG_XML_QUESTION_DESC" IS 'Indica il tag da utilizzare in XML per la descrizione delle domande'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."MANDATORY_TO_SEX" IS 'Indica se la domanda è obbligatoria in base al sesso. Se M maschile, F femminile, null per tutti (uguale a mandatory)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."STYLE_CSS" IS 'Indica lo style css per il componente'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."NEW_LINE" IS 'Indica se la domanda e la risposta devono stare sulla stessa linea'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."POSITION_INDEX" IS 'Indica l''ordine del componente (posizione)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."COLUMNS_RADIOCHECK_GROUP" IS 'Indica il numero di colonne su cui disporre un gruppo di radio button o di check button'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."FOLLOWED_BY_SEPARATOR" IS 'Indica se la domanda è seguita da un separatore '
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLITEMS"."FL_SUMMARY_FIELD" IS 'Indica se il componente viene usato come campo di riepilogo'
