
  CREATE TABLE "DYNAMICFORMS_SVI"."TMPLREPORTS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(300),
	"REF_ACTYPE" NUMBER(10,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_TMPLREPORTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_ACTIVITYTYPE_TMPLREP_1" FOREIGN KEY ("REF_ACTYPE")
	  REFERENCES "DYNAMICFORMS_SVI"."ACTIVITYTYPES" ("ID") ENABLE,
	 CONSTRAINT "FK_ASS_35" FOREIGN KEY ("ID")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLCOMPONENTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLREPORTS"."ID" IS 'Identificativo numerico assegnato dal sistema'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLREPORTS"."NAME" IS 'Nome del template (non è il nome del file che si trova nei metadati)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLREPORTS"."REF_ACTYPE" IS 'Riferimento alla tipologia'
