
  CREATE TABLE "DYNAMICFORMS_SVI"."TMPLANSWER_CMP_MATERIALS"
   (	"ID" NUMBER(10,0),
	"CLASSIFICATION_CODES" VARCHAR2(200),
	"REF_TMPLANSWER" NUMBER(10,0),
	"FL_VISIBLE_MAT_SIZE" NUMBER(1,0) DEFAULT 0,
	"FL_VISIBLE_MAT_TYPE" NUMBER(1,0) DEFAULT 0,
	"FL_VISIBLE_MAT_PRESSURE" NUMBER(1,0) DEFAULT 0,
	"FL_VISIBLE_MAT_PRESSURE_TYPE" NUMBER(1,0) DEFAULT 0,
	"FL_VISIBLE_MAT_ENERGY" NUMBER(1,0) DEFAULT 0,
	 CONSTRAINT "PK_TMPLANSWER_CMP_MATERIALS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_TMPLANSWER_TMPLANS_CMP_MAT" FOREIGN KEY ("REF_TMPLANSWER")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLANSWERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI" 
