
  CREATE TABLE "DYNAMICFORMS_SVI"."TMPLSECTIONS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(300),
	"REF_PARENT" NUMBER(10,0),
	"REF_ACTYPE" NUMBER(10,0) NOT NULL ENABLE,
	"NOTE" VARCHAR2(4000),
	"HIDDEN" NUMBER(1,0) DEFAULT 0,
	"TAG_XML_SECTION" VARCHAR2(200),
	"TAG_XML_SECTION_RATING" VARCHAR2(200),
	"TAG_XML_SECTION_TITLE" VARCHAR2(200),
	"TAG_XML_SECTION_SCORE" VARCHAR2(200),
	"MAIN_COMPONENT" VARCHAR2(200),
	"STYLE_CSS" VARCHAR2(300),
	"REPEATABLE" NUMBER(1,0) DEFAULT 0,
	"COLUMNS_PANELGRID" NUMBER(10,0),
	"POSITION_INDEX" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"READ_ONLY" NUMBER(1,0) DEFAULT 0,
	"FOLLOWED_BY_SEPARATOR" NUMBER(1,0) DEFAULT 0,
	"REPEATABLECODED" NUMBER(1,0) DEFAULT 0,
	"REF_PARAM_VIEW" NUMBER(10,0),
	"REPEATABLECODED_HEADER_HIDDEN" NUMBER(1,0) DEFAULT 0,
	"REPEATABLE_RECORDREMOVEBUTTON" NUMBER(1,0),
	"SECTIONS_UPDATE_TARGET" VARCHAR2(200),
	"REPEATABLE_BTN_USEJSFUNCTION" NUMBER(1,0) DEFAULT 0,
	"REF_ENTRY" NUMBER(10,0),
	"FL_HISTORY_CONTAINER" NUMBER(1,0) DEFAULT 0,
	"FL_REPEATABLE_BUTTONS_VISIBLE" NUMBER(1,0) DEFAULT 1,
	 CHECK (
  HIDDEN IN (0, 1)
) ENABLE,
	 CHECK (
  REPEATABLE IN (0, 1)
) ENABLE,
	 CHECK (
  READ_ONLY IN (0, 1)
) ENABLE,
	 CHECK (
  FOLLOWED_BY_SEPARATOR IN (0, 1)
) ENABLE,
	 CONSTRAINT "PK_TMPLSECTIONS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"  ENABLE,
	 CONSTRAINT "FK_ASS_12" FOREIGN KEY ("ID")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLCOMPONENTS" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLSECTION_ACTYPE_1" FOREIGN KEY ("REF_ACTYPE")
	  REFERENCES "DYNAMICFORMS_SVI"."ACTIVITYTYPES" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLSECTION_TMPLSECTION_2" FOREIGN KEY ("REF_PARENT")
	  REFERENCES "DYNAMICFORMS_SVI"."TMPLSECTIONS" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLSECTION_PARAMVIEW_1" FOREIGN KEY ("REF_PARAM_VIEW")
	  REFERENCES "DYNAMICFORMS_SVI"."PARAM_VIEWS" ("ID") ENABLE,
	 CONSTRAINT "FK_TMPLSECTION_ENTRY" FOREIGN KEY ("REF_ENTRY")
	  REFERENCES "DYNAMICFORMS_SVI"."ENTRIES" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI"

   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."ID" IS 'Identificativo numerico assegnato dal sistema'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."NAME" IS 'Descrizione della sezione'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REF_PARENT" IS 'Riferimento alla sezione di livello superiore'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REF_ACTYPE" IS 'Riferimento alla tipologia'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."NOTE" IS 'Eventuali note della sezione'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."HIDDEN" IS 'Valore che indica se la sezione deve essere visualizzata o meno'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."TAG_XML_SECTION" IS 'Indica il tag da utilizzare in XML per le sezioni'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."TAG_XML_SECTION_RATING" IS 'Indica il tag da utilizzare in XML per il rating delle sezioni'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."TAG_XML_SECTION_TITLE" IS 'Indica il tag da utilizzare in XML per il titolo delle sezioni'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."TAG_XML_SECTION_SCORE" IS 'Indica il tag da utilizzare in XML per lo score delle sezioni'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."MAIN_COMPONENT" IS 'Indica il tipo di componente che ospitera'' le domande e risposte. Se NULL, panel principale'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."STYLE_CSS" IS 'Indica lo style css per il componente'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REPEATABLE" IS 'Indica se i componenti della sezione sono ripetibili'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."COLUMNS_PANELGRID" IS 'Indica il numero di colonne se il componente è un panelGrid'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."POSITION_INDEX" IS 'Indica l''ordine del componente (posizione)'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."READ_ONLY" IS 'Indica se la sezione e tutti i componenti in essa contenuti sono in sola lettura'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."FOLLOWED_BY_SEPARATOR" IS 'Indica se la sezione è seguita da un separatore'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REF_PARAM_VIEW" IS 'Indica il riferimento a param view per i codici da utilizzare se REPEATABLECODED = true'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REPEATABLECODED_HEADER_HIDDEN" IS 'Indica se la testata della sezione ripetibile codificata deve essere nascosta.'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REPEATABLE_RECORDREMOVEBUTTON" IS 'Indica se il bottone remove deve essere aggiunto per ogni singola riga della sezione ripetibile.'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."SECTIONS_UPDATE_TARGET" IS 'Lista di id sezioni che comporranno il tag update del pulsante delle sezioni ripetibili.'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."REPEATABLE_BTN_USEJSFUNCTION" IS 'Indica se utilizzare funzioni javascript per pulsanti + e - delle sezioni ripetibili.'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."FL_HISTORY_CONTAINER" IS 'Indica se la sezione è un contenitore delle risposte precedenti per la sezione ripetibile'
   COMMENT ON COLUMN "DYNAMICFORMS_SVI"."TMPLSECTIONS"."FL_REPEATABLE_BUTTONS_VISIBLE" IS 'Indica se i bottoni +/- della sezione ripetibile sono visibili'
