
  CREATE TABLE "DYNAMICFORMS_SVI"."VALENTINA_TEST"
   (	"ID_SCHEDA" NUMBER(10,0),
	"DESCRIZIONE_SCHEDA" VARCHAR2(50),
	"NOME_SCHEDA" VARCHAR2(50),
	"ASPETTO_SCHEDA" VARCHAR2(50),
	"INFO_SCHEDA" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DYNAMIC_FORMS_SVI" 
