CREATE OR REPLACE FUNCTION DYNAMICFORMS_SVI.FN_GET_BISOGNI_DESCRIP(v_code IN VARCHAR2)
	RETURN VARCHAR2
	IS risposta VARCHAR2(255);
	BEGIN
		SELECT  v.DESCRIPTION
		INTO risposta
		FROM BISOGNI_CONFIG v
		WHERE  v.CODE = v_code  ;
		RETURN (risposta);
END;
