CREATE OR REPLACE FUNCTION DYNAMICFORMS_SVI."GET_VERBAL_NUMBER" (V_ORDER_NUMBER_LIST IN  VARCHAR2, V_SITE_ID IN VARCHAR2)
Return VARCHAR2
As
VERBAL_NUMBER VARCHAR2(300);
CNT NUMBER(8,2);

BEGIN
   CNT  := 0;
   VERBAL_NUMBER := NULL;

   --1. if numberoVerbale already exists for orderNumberList-siteId, then get the existing numberoVerbale
  SELECT COUNT(W.VERBAL_NUMBER) INTO CNT FROM WK_VERBAL_NUMBER_TRACKINGS  W WHERE W.ORDER_NUMBER_LIST=V_ORDER_NUMBER_LIST  AND W.SITE_ID=V_SITE_ID;
  IF( CNT =0 ) THEN
    -- 2. generate new numeroVerbale
	IF(V_SITE_ID = '004' ) THEN
		SELECT TO_CHAR(SYSDATE, 'YYYY')|| TO_CHAR(SITE_ID_4_VERBAL_NUMBER_SEQ.NEXTVAL, 'fm0009') INTO VERBAL_NUMBER from DUAL;
	ELSIF(V_SITE_ID = '005' ) THEN
		SELECT TO_CHAR(SYSDATE, 'YYYY')|| TO_CHAR(SITE_ID_5_VERBAL_NUMBER_SEQ.NEXTVAL, 'fm0009') INTO VERBAL_NUMBER from DUAL;
    END IF;

     --3. insert newly created value
     P_TRACK_VERBAL_NUMBER(V_ORDER_NUMBER_LIST, V_SITE_ID, VERBAL_NUMBER);

   ELSE
     SELECT W.VERBAL_NUMBER INTO VERBAL_NUMBER FROM WK_VERBAL_NUMBER_TRACKINGS  W WHERE W.ORDER_NUMBER_LIST=V_ORDER_NUMBER_LIST  AND W.SITE_ID=V_SITE_ID;

   END IF;
  RETURN VERBAL_NUMBER;
END GET_VERBAL_NUMBER;
